# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    mysql:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
